
type DocumentRequestListsType = {
    'RH': string[];
    'Fiscal': string[];
    'Contábil': string[];
    'Societário': string[];
};

export const documentRequestLists: DocumentRequestListsType = {
    'RH': [
        'Admissão de Funcionários',
        'Ficha de registro de empregado',
        'Contrato de trabalho (CLT, temporário, estágio, autônomo, PJ etc.)',
        'Carteira de Trabalho e Previdência Social (CTPS) – anotações',
        'Documentos pessoais do colaborador (RG, CPF, CNH, Título de Eleitor, Certidão de Nascimento/Casamento)',
        'Comprovante de endereço',
        'Certificado de reservista (para homens)',
        'Comprovante de escolaridade',
        'Atestado de saúde ocupacional admissional (ASO)',
        'Ficha de salário-família (se aplicável)',
        'Declaração de dependentes para IRRF',
        'Termo de ciência de políticas internas (código de conduta, dress code etc.)',
        'Termo de confidencialidade (NDA)',
        'Ficha de EPI (Entrega de Equipamentos de Proteção Individual)',
        'Livro ou ficha de registro de empregados',
        'Controle de ponto (manual, mecânico ou eletrônico)',
        'Folha de pagamento mensal',
        'Recibos de pagamento de salário',
        'Recibos de pagamento de férias',
        'Recibos de pagamento de 13º salário',
        'Recibos de pagamento de horas extras/adicionais',
        'Relatórios de benefícios (vale-transporte, vale-refeição, plano de saúde etc.)',
        'Atualização cadastral de empregados',
        'Plano de cargos e salários',
        'Avaliações de desempenho',
        'Plano de treinamentos e capacitação',
        'Guia de Recolhimento do FGTS (GFIP/SEFIP)',
        'GPS – Guia da Previdência Social (INSS)',
        'RAIS (Relação Anual de Informações Sociais)',
        'DIRF (Declaração do Imposto de Renda Retido na Fonte)',
        'eSocial (eventos periódicos e não periódicos)',
        'CAGED (Cadastro Geral de Empregados e Desempregados – quando aplicável)',
        'PPP (Perfil Profissiográfico Previdenciário)',
        'CAT (Comunicação de Acidente de Trabalho)',
        'PCMSO (Programa de Controle Médico de Saúde Ocupacional)',
        'PPRA/PGR (Programa de Prevenção de Riscos Ambientais / Programa de Gerenciamento de Riscos)',
        'LTCAT (Laudo Técnico das Condições Ambientais de Trabalho)',
        'Termos de adesão ou recusa de vale-transporte',
        'Termos de adesão a plano de saúde ou odontológico',
        'Termo de adesão a programas de participação nos lucros e resultados (PLR)',
        'Documentos de convênios (farmácia, academia etc.)',
        'Políticas de benefícios e incentivos',
        'Aviso de férias',
        'Recibo de pagamento de férias',
        'Controle de férias vencidas e proporcionais',
        'Aviso prévio (trabalhado ou indenizado)',
        'Termo de rescisão do contrato de trabalho (TRCT)',
        'Termo de quitação de rescisão',
        'Termo de homologação de rescisão (quando aplicável)',
        'Guias para saque do FGTS',
        'Requerimento do seguro-desemprego',
        'Atestado de saúde ocupacional demissional (ASO)',
        'Entrega de documentos e bens da empresa',
        'Declaração de quitação de débitos com a empresa',
        'Comunicados internos (circulares, memorandos)',
        'Relatórios de afastamento (médico, maternidade, acidente)',
        'Atestados médicos',
        'Advertências, suspensões e justa causa (registros disciplinares)',
        'Termos de responsabilidade (uso de equipamentos, veículos etc.)',
        'Relatórios de incidentes',
    ],
    'Fiscal': [
        'NF-e (Nota Fiscal eletrônica de produtos – modelo 55)',
        'NFS-e (Nota Fiscal de serviços eletrônica)',
        'NFC-e (Nota Fiscal do consumidor eletrônica)',
        'CT-e (Conhecimento de Transporte eletrônico)',
        'MDF-e (Manifesto Eletrônico de Documentos Fiscais)',
        'DANFE (Documento Auxiliar da NF-e)',
        'DANFSE (Documento Auxiliar da NFS-e)',
        'Cancelamentos e cartas de correção de NF-e',
        'Arquivos XML das notas fiscais emitidas e recebidas',
        'Livros de apuração do ICMS',
        'Livros de apuração do ISSQN',
        'Livros de apuração do IPI',
        'Livros de apuração do PIS e COFINS',
        'Apuração do IRPJ e CSLL',
        'Demonstrativo de apuração do Simples Nacional (DAS)',
        'Apuração de retenções na fonte (IRRF, INSS, ISS, PIS, COFINS, CSLL)',
        'DCTF (Declaração de Débitos e Créditos Tributários Federais)',
        'EFD-Contribuições (PIS e COFINS)',
        'EFD-ICMS/IPI (SPED Fiscal)',
        'DIRF (Declaração do Imposto de Renda Retido na Fonte)',
        'ECD (Escrituração Contábil Digital)',
        'ECF (Escrituração Contábil Fiscal)',
        'GIA (Guia de Informação e Apuração do ICMS)',
        'SINTEGRA (quando exigido pelo estado)',
        'DeSTDA (Declaração de Substituição Tributária, Diferencial de Alíquota e Antecipação)',
        'SEF II ou programas estaduais equivalentes',
        'Declarações específicas exigidas por cada Secretaria da Fazenda Estadual',
        'Declaração eletrônica de ISSQN',
        'DES/DMS (Declaração de Serviços)',
        'Documentos de retenção de ISS na fonte',
        'Guias de recolhimento de taxas municipais (alvará, fiscalização etc.)',
        'DARF (Documento de Arrecadação de Receitas Federais)',
        'DAS (Documento de Arrecadação do Simples Nacional)',
        'GNRE (Guia Nacional de Recolhimento de Tributos Estaduais)',
        'GARE (Guia de Arrecadação Estadual – em alguns estados)',
        'GPS (Guia da Previdência Social) – quando vinculada a retenções fiscais',
        'Guias de ISSQN municipais',
        'Certidões negativas de débitos (CND – Receita Federal, FGTS, INSS, estadual e municipal)',
        'Relatórios de movimentação fiscal mensal',
        'Registros de substituição tributária (ICMS-ST)',
        'Documentos de importação e exportação (DI, DUE, notas de importação)',
        'Documentos de inventário fiscal',
        'Documentos de conferência e auditoria fiscal',
        'Planilhas de controle de retenções e compensações tributárias',
        'Protocolos e comprovantes de entrega de declarações',
    ],
    'Contábil': [
        'Livro Diário (impresso ou eletrônico – SPED)',
        'Livro Razão',
        'Termos de abertura e encerramento dos livros contábeis',
        'Balancete de verificação',
        'Balanço Patrimonial',
        'Demonstração do Resultado do Exercício (DRE)',
        'Demonstração de Lucros ou Prejuízos Acumulados (DLPA)',
        'Demonstração do Fluxo de Caixa (DFC)',
        'Demonstração do Valor Adicionado (DVA), quando exigida',
        'Relatórios de conciliações contábeis',
    ],
    'Societário': [
        'Contrato Social (Sociedade Limitada)',
        'Estatuto Social (Sociedade Anônima ou associação)',
        'Requerimento de Empresário Individual',
        'Ata de constituição (para cooperativas e associações)',
        'Ficha de Cadastro Nacional (FCN)',
        'DBE – Documento Básico de Entrada (Receita Federal)',
        'Ficha de inscrição municipal e estadual',
        'Alteração do Contrato Social ou Estatuto Social',
        'Ata de reunião ou assembleia geral',
        'Instrumento de cessão e transferência de quotas ou ações',
        'Instrumento de aumento ou redução de capital',
        'Ata de eleição e posse de administradores ou diretores',
        'Certidões negativas de débitos (federal, estadual, municipal, FGTS)',
        'Alvará de funcionamento',
        'Licenças específicas (sanitária, ambiental, bombeiros etc.)',
        'Inscrição estadual (quando aplicável)',
        'Inscrição municipal',
        'Comprovante de enquadramento ou desenquadramento do Simples Nacional',
        'Distrato social (Sociedade Limitada)',
        'Ata de dissolução e liquidação (S/A, cooperativas, associações)',
        'DBE de baixa de CNPJ',
        'Requerimento de baixa na junta comercial ou cartório',
        'Baixa de inscrições estadual e municipal',
        'Livro de atas de reuniões e assembleias',
        'Livro de registro de sócios ou acionistas',
        'Livro de presença de assembleias e reuniões',
        'Procurações e substabelecimentos',
        'Acordos de sócios ou acionistas',
    ],
};
