type DocumentRequestListsType = {
    'RH': string[];
    'Fiscal': string[];
    'Contábil': string[];
    'Societário': string[];
};

export const documentRequestLists: DocumentRequestListsType = {
    'RH': [
        'Admissão de Funcionários',
        'Rescisão de Contrato de Funcionário',
        'Advertências, suspensões e justa causa (registros disciplinares)',
        'Atestado de saúde ocupacional admissional (ASO)',
        'Atestado de saúde ocupacional demissional (ASO)',
        'Atestados médicos',
        'Atualização cadastral de empregados',
        'Avaliações de desempenho',
        'Aviso de férias',
        'Aviso prévio (trabalhado ou indenizado)',
        'CAGED (Cadastro Geral de Empregados e Desempregados – quando aplicável)',
        'Carteira de Trabalho e Previdência Social (CTPS) – anotações',
        'CAT (Comunicação de Acidente de Trabalho)',
        'Certificado de reservista (para homens)',
        'Comunicados internos (circulares, memorandos)',
        'Comprovante de endereço',
        'Comprovante de escolaridade',
        'Contrato de trabalho (CLT, temporário, estágio, autônomo, PJ etc.)',
        'Controle de férias vencidas e proporcionais',
        'Controle de ponto (manual, mecânico ou eletrônico)',
        'Declaração de dependentes para IRRF',
        'Declaração de quitação de débitos com a empresa',
        'DIRF (Declaração do Imposto de Renda Retido na Fonte)',
        'Documentos de convênios (farmácia, academia etc.)',
        'Documentos pessoais do colaborador (RG, CPF, CNH, Título de Eleitor, Certidão de Nascimento/Casamento)',
        'Entrega de documentos e bens da empresa',
        'eSocial (eventos periódicos e não periódicos)',
        'Ficha de EPI (Entrega de Equipamentos de Proteção Individual)',
        'Ficha de registro de empregado',
        'Ficha de salário-família (se aplicável)',
        'Folha de pagamento mensal',
        'GPS – Guia da Previdência Social (INSS)',
        'Guia de Recolhimento do FGTS (GFIP/SEFIP)',
        'Guias para saque do FGTS',
        'Livro ou ficha de registro de empregados',
        'LTCAT (Laudo Técnico das Condições Ambientais de Trabalho)',
        'PCMSO (Programa de Controle Médico de Saúde Ocupacional)',
        'Plano de cargos e salários',
        'Plano de treinamentos e capacitação',
        'Políticas de benefícios e incentivos',
        'PPP (Perfil Profissiográfico Previdenciário)',
        'PPRA/PGR (Programa de Prevenção de Riscos Ambientais / Programa de Gerenciamento de Riscos)',
        'RAIS (Relação Anual de Informações Sociais)',
        'Recibos de pagamento de 13º salário',
        'Recibos de pagamento de férias',
        'Recibos de pagamento de horas extras/adicionais',
        'Recibos de pagamento de salário',
        'Relatórios de afastamento (médico, maternidade, acidente)',
        'Relatórios de benefícios (vale-transporte, vale-refeição, plano de saúde etc.)',
        'Relatórios de incidentes',
        'Requerimento do seguro-desemprego',
        'Termo de ciência de políticas internas (código de conduta, dress code etc.)',
        'Termo de confidencialidade (NDA)',
        'Termo de homologação de rescisão (quando aplicável)',
        'Termo de quitação de rescisão',
        'Termo de rescisão do contrato de trabalho (TRCT)',
        'Termos de adesão a plano de saúde ou odontológico',
        'Termos de adesão a programas de participação nos lucros e resultados (PLR)',
        'Termos de adesão ou recusa de vale-transporte',
        'Termos de responsabilidade (uso de equipamentos, veículos etc.)'
    ].sort((a, b) => a.localeCompare(b)),
    'Fiscal': [
        'Apuração de retenções na fonte (IRRF, INSS, ISS, PIS, COFINS, CSLL)',
        'Apuração do IRPJ e CSLL',
        'Arquivos XML das notas fiscais emitidas e recebidas',
        'Cancelamentos e cartas de correção de NF-e',
        'Certidões negativas de débitos (CND – Receita Federal, FGTS, INSS, estadual e municipal)',
        'CT-e (Conhecimento de Transporte eletrônico)',
        'DANFE (Documento Auxiliar da NF-e)',
        'DANFSE (Documento Auxiliar da NFS-e)',
        'DARF (Documento de Arrecadação de Receitas Federais)',
        'DAS (Documento de Arrecadação do Simples Nacional)',
        'DCTF (Declaração de Débitos e Créditos Tributários Federais)',
        'Declaração eletrônica de ISSQN',
        'Declarações específicas exigidas por cada Secretaria da Fazenda Estadual',
        'Demonstrativo de apuração do Simples Nacional (DAS)',
        'DES/DMS (Declaração de Serviços)',
        'DeSTDA (Declaração de Substituição Tributária, Diferencial de Alíquota e Antecipação)',
        'DIRF (Declaração do Imposto de Renda Retido na Fonte)',
        'Documentos de conferência e auditoria fiscal',
        'Documentos de importação e exportação (DI, DUE, notas de importação)',
        'Documentos de inventário fiscal',
        'Documentos de retenção de ISS na fonte',
        'ECD (Escrituração Contábil Digital)',
        'ECF (Escrituração Contábil Fiscal)',
        'EFD-Contribuições (PIS e COFINS)',
        'EFD-ICMS/IPI (SPED Fiscal)',
        'GARE (Guia de Arrecadação Estadual – em alguns estados)',
        'GIA (Guia de Informação e Apuração do ICMS)',
        'GNRE (Guia Nacional de Recolhimento de Tributos Estaduais)',
        'GPS (Guia da Previdência Social) – quando vinculada a retenções fiscais',
        'Guias de ISSQN municipais',
        'Guias de recolhimento de taxas municipais (alvará, fiscalização etc.)',
        'Livros de apuração do ICMS',
        'Livros de apuração do IPI',
        'Livros de apuração do ISSQN',
        'Livros de apuração do PIS e COFINS',
        'MDF-e (Manifesto Eletrônico de Documentos Fiscais)',
        'NF-e (Nota Fiscal eletrônica de produtos – modelo 55)',
        'NFC-e (Nota Fiscal do consumidor eletrônica)',
        'NFS-e (Nota Fiscal de serviços eletrônica)',
        'Planilhas de controle de retenções e compensações tributárias',
        'Protocolos e comprovantes de entrega de declarações',
        'Registros de substituição tributária (ICMS-ST)',
        'Relatórios de movimentação fiscal mensal',
        'SEF II ou programas estaduais equivalentes',
        'SINTEGRA (quando exigido pelo estado)'
    ].sort((a, b) => a.localeCompare(b)),
    'Contábil': [
        'Balanço Patrimonial',
        'Balancete de verificação',
        'Demonstração de Lucros ou Prejuízos Acumulados (DLPA)',
        'Demonstração do Fluxo de Caixa (DFC)',
        'Demonstração do Resultado do Exercício (DRE)',
        'Demonstração do Valor Adicionado (DVA), quando exigida',
        'Livro Diário (impresso ou eletrônico – SPED)',
        'Livro Razão',
        'Relatórios de conciliações contábeis',
        'Termos de abertura e encerramento dos livros contábeis'
    ].sort((a, b) => a.localeCompare(b)),
    'Societário': [
        'Acordos de sócios ou acionistas',
        'Alteração do Contrato Social ou Estatuto Social',
        'Alvará de funcionamento',
        'Ata de constituição (para cooperativas e associações)',
        'Ata de dissolução e liquidação (S/A, cooperativas, associações)',
        'Ata de eleição e posse de administradores ou diretores',
        'Ata de reunião ou assembleia geral',
        'Baixa de inscrições estadual e municipal',
        'Certidões negativas de débitos (federal, estadual, municipal, FGTS)',
        'Comprovante de enquadramento ou desenquadramento do Simples Nacional',
        'Contrato Social (Sociedade Limitada)',
        'DBE – Documento Básico de Entrada (Receita Federal)',
        'DBE de baixa de CNPJ',
        'Distrato social (Sociedade Limitada)',
        'Estatuto Social (Sociedade Anônima ou associação)',
        'Ficha de Cadastro Nacional (FCN)',
        'Ficha de inscrição municipal e estadual',
        'Inscrição estadual (quando aplicável)',
        'Inscrição municipal',
        'Instrumento de aumento ou redução de capital',
        'Instrumento de cessão e transferência de quotas ou ações',
        'Licenças específicas (sanitária, ambiental, bombeiros etc.)',
        'Livro de atas de reuniões e assembleias',
        'Livro de presença de assembleias e reuniões',
        'Livro de registro de sócios ou acionistas',
        'Procurações e substabelecimentos',
        'Requerimento de Empresário Individual',
        'Requerimento de baixa na junta comercial ou cartório'
    ].sort((a, b) => a.localeCompare(b)),
};